### ISSUE TITLE
TypeError: tmp.length is not a function

### ISSUE THREAD

**Issue by bmachek** [unparagoned/njsTuya#5]
When I run:
node njstuya.js -ip xx -id xx OFF

I get the error message from the subject.
Did anyone yet have this error?

Stacktrace:
TypeError: tmp.length is not a function
    at forge.aes.Algorithm.initialize (/etc/openhab2/scripts/node_modules/node-forge/lib/aes.js:203:19)
    at new forge.cipher.BlockCipher (/etc/openhab2/scripts/node_modules/node-forge/lib/cipher.js:118:18)
    at Object.forge.cipher.createCipher (/etc/openhab2/scripts/node_modules/node-forge/lib/cipher.js:42:10)
    at new TuyaDevice (/etc/openhab2/scripts/node_modules/tuyapi/index.js:65:43)
    at Object.<anonymous> (/etc/openhab2/scripts/node_modules/tuyapi/njstuya.js:26:12)
    at Module._compile (module.js:577:32)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)

Please advise, if additional data is required.

Cheers,
Bastian

**Comment by bmachek** [comment]
Just noticed this is a duplicate. Sorry.
